-- Users: every principal that can create or change something in Elysium. See docs/auth.md.
--
-- People sign in through Ory Kratos, which holds their passwords, passkeys, authenticators,
-- and sessions; a person's row names its Kratos identity. Machines (the system, Elysia, and
-- coding agents) are seeded here, can never sign in, and exist so that every row can name
-- who created it.

-- What a principal may do. People are admins, members, or guests; machines are agents or the
-- system. A pending person has no role until an admin approves them.
CREATE TYPE user_role AS ENUM (
    'admin',
    'member',
    'guest',
    'agent',
    'system'
);

-- Where a person's account stands. Machines have none.
CREATE TYPE user_status AS ENUM (
    -- Signed up, waiting for an admin. Can sign in, and reach nothing but their own account.
    'pending',
    'active',
    -- Refused at sign-in and on every request. Never deleted: rows they created name them.
    'disabled'
);

CREATE TABLE users (
    -- Generated by the API (UUIDv7) for people; fixed for the seeded machines below.
    id UUID PRIMARY KEY,
    -- The Kratos identity a person signs in as. Machines have none.
    kratos_identity_id UUID UNIQUE,
    -- A person's email and name, as Kratos last reported them. Kratos is the source of truth;
    -- this copy lets lists and "created by" show people without asking Kratos.
    email TEXT UNIQUE,
    name TEXT NOT NULL,
    role user_role,
    status user_status,
    -- When they were approved; NULL for machines and pending people. The first person is
    -- approved as they sign up.
    approved_at TIMESTAMPTZ,
    -- When they last made a request, to within a few minutes.
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT users_name_length CHECK (char_length(name) BETWEEN 1 AND 100),
    CONSTRAINT users_email_length CHECK (char_length(email) BETWEEN 3 AND 320),
    CONSTRAINT users_email_lowercase CHECK (email = lower(email)),
    -- A principal is exactly one of these. A machine can never hold a Kratos identity, so it
    -- can never sign in; a person can never hold a machine's role.
    CONSTRAINT users_person_or_machine CHECK (
        (
            kratos_identity_id IS NULL
            AND email IS NULL
            AND status IS NULL
            AND role IS NOT NULL
            AND role IN ('agent', 'system')
        )
        OR (
            kratos_identity_id IS NOT NULL
            AND email IS NOT NULL
            AND status IS NOT NULL
            AND (role IS NULL OR role IN ('admin', 'member', 'guest'))
        )
    ),
    -- A person has a role exactly when they are no longer pending.
    CONSTRAINT users_pending_has_no_role CHECK (status IS NULL OR (status = 'pending') = (role IS NULL))
);

SELECT diesel_manage_updated_at('users');

-- Elysium's machines. The ids are fixed so code and tests can name them.
INSERT INTO users (id, name, role) VALUES
    -- Owns what nobody in particular did: rows that predate accounts, what the watcher imports.
    ('00000000-0000-0000-0000-000000000001', 'Elysium', 'system'),
    -- Elysium's AI assistant.
    ('00000000-0000-0000-0000-000000000002', 'Elysia', 'agent'),
    -- Every coding session's agent. History names the session as well.
    ('00000000-0000-0000-0000-000000000003', 'Coding agent', 'agent');

-- Workspace-wide settings admins change. One row, always present.
CREATE TABLE workspace_settings (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE,
    -- Whether anyone may sign up. The first person may sign up either way.
    signup_open BOOLEAN NOT NULL DEFAULT TRUE,
    -- Whether every person must enroll an authenticator app before reaching the workspace.
    require_mfa BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by UUID NOT NULL REFERENCES users (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT workspace_settings_one_row CHECK (singleton)
);

SELECT diesel_manage_updated_at('workspace_settings');

INSERT INTO workspace_settings (updated_by) VALUES ('00000000-0000-0000-0000-000000000001');

-- What admins did to accounts and workspace settings, and what people did to their own: one
-- row per change, with the values before and after.
CREATE TABLE user_events (
    -- Generated by the API (UUIDv7), so ids order events the way they happened.
    id UUID PRIMARY KEY,
    -- Whose account changed; NULL for a workspace setting, or once a rejected sign-up is gone.
    user_id UUID REFERENCES users (id) ON DELETE SET NULL,
    -- Who changed it. A person signing up or editing their own profile is their own actor, so
    -- this is NULL too once their rejected sign-up is gone.
    actor_id UUID REFERENCES users (id) ON DELETE SET NULL,
    kind TEXT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT user_events_kind_shape CHECK (kind ~ '^[a-z][a-z_]{0,63}$'),
    CONSTRAINT user_events_data_object CHECK (jsonb_typeof(data) = 'object')
);

CREATE INDEX user_events_user_id_idx ON user_events (user_id, id) WHERE user_id IS NOT NULL;
