-- Global environment variables, passed into every coding session's satellite thread. Every
-- value is sealed by the API (XChaCha20-Poly1305, keyed by ELYSIUM_ENCRYPTION_KEY, bound to
-- the row id) before it reaches this table, secret or not, so every row is handled the
-- same way and Postgres only ever holds ciphertext.

CREATE TABLE environment_variables (
    -- Generated by the API (UUIDv7) so the id exists before the value is sealed.
    id UUID PRIMARY KEY,
    key TEXT NOT NULL,
    value_encrypted BYTEA NOT NULL,
    -- Whether Elysium hides the value from every response and the satellite scrubs it from
    -- thread output. The agent itself can always read it.
    is_secret BOOLEAN NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT environment_variables_key_unique UNIQUE (key),
    -- A name every shell and process accepts: a letter or underscore, then letters, digits,
    -- or underscores.
    CONSTRAINT environment_variables_key_shape CHECK (key ~ '^[A-Za-z_][A-Za-z0-9_]*$'),
    CONSTRAINT environment_variables_key_length CHECK (char_length(key) <= 128),
    CONSTRAINT environment_variables_description_length CHECK (char_length(description) <= 500),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT environment_variables_value_sealed CHECK (octet_length(value_encrypted) >= 41)
);

SELECT diesel_manage_updated_at('environment_variables');
