-- Mail domains the bundled mail server hosts. One server hosts any number of them on one
-- set of ports; a self-hosted mailbox belongs to exactly one.
--
-- The server is now created and administered by the API through Docker, so its
-- administrator row starts over with the new shape, and self-hosted mailboxes, which
-- cannot name a domain on that server, are removed with it.

DELETE FROM mail_accounts WHERE kind = 'self_hosted';
DROP TABLE mail_servers;

CREATE TABLE mail_servers (
    -- Generated by the API (UUIDv7) so the id exists before the secret is sealed.
    id UUID PRIMARY KEY,
    -- The name the server answers as, such as mail.example.com. Every domain's MX
    -- record points here.
    hostname TEXT NOT NULL,
    admin_username TEXT NOT NULL,
    admin_secret_encrypted BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT mail_servers_hostname_shape CHECK (
        hostname ~ '^[a-z0-9.-]+\.[a-z0-9-]+$' AND char_length(hostname) <= 253
    ),
    CONSTRAINT mail_servers_admin_username_length CHECK (char_length(admin_username) BETWEEN 1 AND 320),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT mail_servers_admin_secret_sealed CHECK (octet_length(admin_secret_encrypted) >= 41)
);

-- Elysium runs exactly one mail server, so the table holds at most one row.
CREATE UNIQUE INDEX mail_servers_singleton ON mail_servers ((true));

CREATE TABLE mail_domains (
    id UUID PRIMARY KEY,
    -- Stored lowercase, so uniqueness is case-insensitive.
    name TEXT NOT NULL,
    -- Stalwart's id for the domain, needed to remove it there.
    stalwart_id TEXT NOT NULL,
    -- The domain the server was created with. Stalwart keeps it as its default, so it
    -- cannot be removed.
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT mail_domains_name_unique UNIQUE (name),
    CONSTRAINT mail_domains_name_shape CHECK (
        name ~ '^[a-z0-9.-]+\.[a-z0-9-]+$' AND char_length(name) <= 253
    )
);

CREATE UNIQUE INDEX mail_domains_one_default ON mail_domains (is_default) WHERE is_default;

ALTER TABLE mail_accounts
    -- The domain a self_hosted mailbox lives on. A domain with mailboxes cannot be removed.
    ADD COLUMN mail_domain_id UUID REFERENCES mail_domains (id) ON DELETE RESTRICT,
    ADD CONSTRAINT mail_accounts_mail_domain_self_hosted CHECK ((kind = 'self_hosted') = (mail_domain_id IS NOT NULL));

CREATE INDEX mail_accounts_mail_domain_id ON mail_accounts (mail_domain_id);
