-- Coding sessions are numbered 1, 2, 3, ... so people can name them ("thread 12") and
-- read them in URLs. The API reserves a number from the identity's sequence before it
-- opens the thread, then inserts the row with that number; see docs/coding.md.
--
-- A UUID has no number to become, so every session is dropped. Delete sessions through
-- the API before running this: that destroys their threads, which would otherwise keep
-- running on their satellites, unrecorded, until their idle TTL collects them.

DELETE FROM coding_sessions;

-- The table is empty, so the USING expression is never evaluated; it only satisfies the
-- syntax. Changing the type in place keeps `id` as the first column.
ALTER TABLE coding_sessions ALTER COLUMN id TYPE BIGINT USING 0;

-- BY DEFAULT, not ALWAYS: the API inserts the number it reserved.
ALTER TABLE coding_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
