-- Initiatives: goals that end, grouping action items and carrying the progress bar. See
-- docs/action-items.md.

CREATE TYPE initiative_state AS ENUM (
    'active',
    'achieved',
    'abandoned'
);

CREATE TABLE initiatives (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    target_at TIMESTAMPTZ,
    state initiative_state NOT NULL DEFAULT 'active',
    -- Soft delete: hidden everywhere, restorable from its history.
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT initiatives_name_length CHECK (char_length(name) BETWEEN 1 AND 200),
    CONSTRAINT initiatives_description_length CHECK (char_length(description) <= 20000)
);

SELECT diesel_manage_updated_at('initiatives');

-- The projects an initiative belongs to; one with none shows under "No project".
CREATE TABLE initiative_projects (
    initiative_id UUID NOT NULL REFERENCES initiatives (id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (initiative_id, project_id)
);

CREATE INDEX initiative_projects_project_id_idx ON initiative_projects (project_id);

-- Every span an item spent in an initiative. Leaving closes the span instead of deleting
-- it, and rejoining opens a new one, so the burnup chart can be drawn for any moment.
CREATE TABLE initiative_items (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    initiative_id UUID NOT NULL REFERENCES initiatives (id) ON DELETE CASCADE,
    action_item_id UUID NOT NULL REFERENCES action_items (id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL,
    left_at TIMESTAMPTZ,

    CONSTRAINT initiative_items_span_order CHECK (left_at >= joined_at)
);

-- An item is in an initiative at most once at a time.
CREATE UNIQUE INDEX initiative_items_current_unique
    ON initiative_items (initiative_id, action_item_id)
    WHERE left_at IS NULL;

-- Finds an item's initiatives; the unique index above serves an initiative's items.
CREATE INDEX initiative_items_action_item_id_idx ON initiative_items (action_item_id);
