-- Action items: one commitment of attention each, wherever it came from. See
-- docs/action-items.md. An item holds only what no provider has: its triage state,
-- priority, due date, snooze, who it waits on, and who owns it.

CREATE TYPE action_item_state AS ENUM (
    'inbox',
    'open',
    'resolved',
    'dismissed'
);

-- Declared most urgent first, so ascending order on the column is Next's priority order.
CREATE TYPE action_item_priority AS ENUM (
    'urgent',
    'high',
    'normal',
    'low'
);

-- Whose list an item is on. There is no users table yet, so someone other than the user
-- is recorded by the name or address a provider reports, and nobody means a linked issue
-- with no assignee.
CREATE TYPE action_item_owner_kind AS ENUM (
    'user',
    'other',
    'nobody'
);

CREATE TABLE action_items (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    title TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    state action_item_state NOT NULL,
    priority action_item_priority NOT NULL DEFAULT 'normal',
    due_at TIMESTAMPTZ,
    -- Hidden from Next until this moment passes.
    snoozed_until TIMESTAMPTZ,
    -- Someone else owes the next step: a name or an address.
    waiting_on TEXT,
    owner_kind action_item_owner_kind NOT NULL DEFAULT 'user',
    owner_name TEXT,
    -- When the item last reached its current state, for initiative burnup charts.
    resolved_at TIMESTAMPTZ,
    dismissed_at TIMESTAMPTZ,
    -- Soft delete: hidden everywhere, restorable from its history.
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT action_items_title_length CHECK (char_length(title) BETWEEN 1 AND 500),
    CONSTRAINT action_items_notes_length CHECK (char_length(notes) <= 20000),
    CONSTRAINT action_items_waiting_on_length CHECK (char_length(waiting_on) BETWEEN 1 AND 320),
    CONSTRAINT action_items_owner_name_length CHECK (char_length(owner_name) BETWEEN 1 AND 320),
    CONSTRAINT action_items_owner_name_set CHECK ((owner_kind = 'other') = (owner_name IS NOT NULL)),
    CONSTRAINT action_items_resolved_at_set CHECK ((state = 'resolved') = (resolved_at IS NOT NULL)),
    CONSTRAINT action_items_dismissed_at_set CHECK ((state = 'dismissed') = (dismissed_at IS NOT NULL))
);

SELECT diesel_manage_updated_at('action_items');

-- Serves Next and the state filters, which only ever look at live items.
CREATE INDEX action_items_live_state_idx ON action_items (state) WHERE deleted_at IS NULL;

-- The projects an item belongs to; an item with none shows under "No project".
CREATE TABLE action_item_projects (
    action_item_id UUID NOT NULL REFERENCES action_items (id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (action_item_id, project_id)
);

-- Finds a project's items; the primary key already serves an item's projects.
CREATE INDEX action_item_projects_project_id_idx ON action_item_projects (project_id);
