-- Links: the external things action items and initiatives point at, the provider writes
-- that have not landed yet, how far the watcher has read each credential, and the done
-- transition chosen for each Jira project. See docs/action-items.md.
--
-- A link reaches its provider through exactly one credential of that provider. Deleting the
-- credential deletes the links that went through it: Elysium can no longer reach what they
-- point at, and the items and initiatives themselves stay.

CREATE TYPE link_provider AS ENUM (
    'jira',
    'github'
);

-- What an item links to.
CREATE TYPE link_kind AS ENUM (
    'issue',
    'pull_request'
);

-- What an initiative links to: a container whose children become its items.
CREATE TYPE container_kind AS ENUM (
    'epic',
    'filter',
    'milestone',
    'label'
);

-- A linked thing's state as the provider last reported it. The watcher acts on a change
-- of this value, never on the value alone, so an item the user reopened stays open while
-- its issue stays done.
CREATE TYPE link_state AS ENUM (
    'open',
    'done',
    'not_planned',
    'merged',
    'closed_unmerged'
);

-- A provider write Elysium owes and has not yet landed.
CREATE TYPE link_write_kind AS ENUM (
    'close',
    'comment'
);

CREATE TABLE action_item_links (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    action_item_id UUID NOT NULL REFERENCES action_items (id) ON DELETE CASCADE,
    provider link_provider NOT NULL,
    kind link_kind NOT NULL,
    jira_credential_id UUID REFERENCES jira_credentials (id) ON DELETE CASCADE,
    github_credential_id UUID REFERENCES github_credentials (id) ON DELETE CASCADE,
    -- What the thing is, for good: Jira's issue id, which survives a move to another
    -- project, or GitHub's owner/name#number.
    external_id TEXT NOT NULL,
    -- What a person reads and a call names: ELY-12, or owner/name#12.
    external_key TEXT NOT NULL,
    url TEXT NOT NULL,
    -- The title as last read, for lists; pages read it live.
    title TEXT NOT NULL DEFAULT '',
    -- Where comments are posted, and whose assignee owns the item.
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    observed_state link_state NOT NULL,
    -- Whose the thing is as last read, in the item's own terms: the credential's own account
    -- is the user. A change of it moves a primary link's item to the new owner.
    observed_owner_kind action_item_owner_kind NOT NULL,
    observed_owner_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT action_item_links_credential CHECK (
        (provider::text = 'jira' AND jira_credential_id IS NOT NULL AND github_credential_id IS NULL)
        OR (provider::text = 'github' AND github_credential_id IS NOT NULL AND jira_credential_id IS NULL)
    ),
    -- Jira links issues; GitHub links issues and pull requests.
    CONSTRAINT action_item_links_kind CHECK (provider::text = 'github' OR kind::text = 'issue'),
    CONSTRAINT action_item_links_external_id_length CHECK (char_length(external_id) BETWEEN 1 AND 300),
    CONSTRAINT action_item_links_external_key_length CHECK (char_length(external_key) BETWEEN 1 AND 300),
    CONSTRAINT action_item_links_url_shape CHECK (url ~ '^https://' AND char_length(url) <= 2048),
    CONSTRAINT action_item_links_title_length CHECK (char_length(title) <= 1000),
    CONSTRAINT action_item_links_observed_owner_name_set
        CHECK ((observed_owner_kind = 'other') = (observed_owner_name IS NOT NULL)),
    CONSTRAINT action_item_links_observed_owner_name_length CHECK (char_length(observed_owner_name) BETWEEN 1 AND 320)
);

SELECT diesel_manage_updated_at('action_item_links');

-- An item has at most one primary link.
CREATE UNIQUE INDEX action_item_links_primary_unique
    ON action_item_links (action_item_id)
    WHERE is_primary;

-- One external thing is one item, so work is never tracked twice. These also serve the
-- watcher, which reads a credential's links.
CREATE UNIQUE INDEX action_item_links_jira_unique
    ON action_item_links (jira_credential_id, kind, external_id)
    WHERE jira_credential_id IS NOT NULL;
CREATE UNIQUE INDEX action_item_links_github_unique
    ON action_item_links (github_credential_id, kind, external_id)
    WHERE github_credential_id IS NOT NULL;

-- An item's links, read on nearly every item write, and the cascade from action_items.
CREATE INDEX action_item_links_action_item_id_idx ON action_item_links (action_item_id);

CREATE TABLE initiative_links (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    initiative_id UUID NOT NULL REFERENCES initiatives (id) ON DELETE CASCADE,
    provider link_provider NOT NULL,
    kind container_kind NOT NULL,
    jira_credential_id UUID REFERENCES jira_credentials (id) ON DELETE CASCADE,
    github_credential_id UUID REFERENCES github_credentials (id) ON DELETE CASCADE,
    -- An epic's issue id, a saved filter's id, owner/name#<milestone number>, or
    -- owner/name:<label>.
    external_id TEXT NOT NULL,
    -- ELY-7 for an epic; otherwise the same as external_id.
    external_key TEXT NOT NULL,
    url TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    -- When the watcher last read every child, and why it could not when it could not.
    synced_at TIMESTAMPTZ,
    sync_error TEXT,
    -- The container held more children than the watcher reads.
    truncated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT initiative_links_credential CHECK (
        (provider::text = 'jira' AND jira_credential_id IS NOT NULL AND github_credential_id IS NULL)
        OR (provider::text = 'github' AND github_credential_id IS NOT NULL AND jira_credential_id IS NULL)
    ),
    -- Jira contains by epic or saved filter; GitHub by milestone or label.
    CONSTRAINT initiative_links_kind CHECK (
        (provider::text = 'jira' AND kind::text IN ('epic', 'filter'))
        OR (provider::text = 'github' AND kind::text IN ('milestone', 'label'))
    ),
    CONSTRAINT initiative_links_external_id_length CHECK (char_length(external_id) BETWEEN 1 AND 300),
    CONSTRAINT initiative_links_external_key_length CHECK (char_length(external_key) BETWEEN 1 AND 300),
    CONSTRAINT initiative_links_url_shape CHECK (url ~ '^https://' AND char_length(url) <= 2048),
    CONSTRAINT initiative_links_title_length CHECK (char_length(title) <= 1000),
    CONSTRAINT initiative_links_sync_error_length CHECK (char_length(sync_error) <= 2000)
);

SELECT diesel_manage_updated_at('initiative_links');

-- A container is linked to an initiative once.
CREATE UNIQUE INDEX initiative_links_jira_unique
    ON initiative_links (initiative_id, jira_credential_id, kind, external_id)
    WHERE jira_credential_id IS NOT NULL;
CREATE UNIQUE INDEX initiative_links_github_unique
    ON initiative_links (initiative_id, github_credential_id, kind, external_id)
    WHERE github_credential_id IS NOT NULL;
CREATE INDEX initiative_links_jira_credential_id_idx ON initiative_links (jira_credential_id);
CREATE INDEX initiative_links_github_credential_id_idx ON initiative_links (github_credential_id);

-- The container that brought an item into an initiative, so a child that leaves the
-- container leaves the initiative too. NULL for an item added by hand.
ALTER TABLE initiative_items
    ADD COLUMN via_link_id UUID REFERENCES initiative_links (id) ON DELETE SET NULL;

CREATE INDEX initiative_items_via_link_id_idx
    ON initiative_items (via_link_id)
    WHERE via_link_id IS NOT NULL;

CREATE TABLE action_item_link_writes (
    -- Generated by the API (UUIDv7), so ids order writes the way they were owed.
    id UUID PRIMARY KEY,
    link_id UUID NOT NULL REFERENCES action_item_links (id) ON DELETE CASCADE,
    kind link_write_kind NOT NULL,
    -- The comment to post; deleting it before it lands drops the write.
    comment_id UUID REFERENCES action_item_comments (id) ON DELETE CASCADE,
    attempts INTEGER NOT NULL DEFAULT 0,
    -- The provider's last answer, or why the write is waiting.
    last_error TEXT,
    last_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT action_item_link_writes_comment_set CHECK ((kind::text = 'comment') = (comment_id IS NOT NULL)),
    CONSTRAINT action_item_link_writes_attempts CHECK (attempts >= 0),
    CONSTRAINT action_item_link_writes_last_error_length CHECK (char_length(last_error) <= 2000)
);

-- A link owes at most one close.
CREATE UNIQUE INDEX action_item_link_writes_close_unique
    ON action_item_link_writes (link_id)
    WHERE kind = 'close';

CREATE INDEX action_item_link_writes_link_id_idx ON action_item_link_writes (link_id, id);

-- How far the watcher has read each credential: everything updated before `watched_through`
-- has been applied.
CREATE TABLE link_watch_cursors (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    jira_credential_id UUID UNIQUE REFERENCES jira_credentials (id) ON DELETE CASCADE,
    github_credential_id UUID UNIQUE REFERENCES github_credentials (id) ON DELETE CASCADE,
    watched_through TIMESTAMPTZ NOT NULL,
    -- Why the latest pass over this credential failed; NULL when it succeeded.
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT link_watch_cursors_one_credential
        CHECK (num_nonnulls(jira_credential_id, github_credential_id) = 1),
    CONSTRAINT link_watch_cursors_last_error_length CHECK (char_length(last_error) <= 2000)
);

SELECT diesel_manage_updated_at('link_watch_cursors');

-- The done transition chosen for a Jira project, as the status it leads into. Only a choice
-- the user made is stored: a project with exactly one done status needs none.
CREATE TABLE jira_done_transitions (
    jira_credential_id UUID NOT NULL REFERENCES jira_credentials (id) ON DELETE CASCADE,
    project_key TEXT NOT NULL,
    status_id TEXT NOT NULL,
    status_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (jira_credential_id, project_key),
    CONSTRAINT jira_done_transitions_project_key_shape CHECK (project_key ~ '^[A-Z][A-Z0-9_]{1,254}$'),
    CONSTRAINT jira_done_transitions_status_id_shape CHECK (status_id ~ '^[0-9]{1,19}$'),
    CONSTRAINT jira_done_transitions_status_name_length CHECK (char_length(status_name) BETWEEN 1 AND 255)
);

SELECT diesel_manage_updated_at('jira_done_transitions');
