-- Studio: single assets made by agents, one item per asset. See docs/studio.md. An item
-- runs on coding sessions; this is what Studio adds around them: the item, the files its
-- agents produced, and the drawn feedback sent back to them.

CREATE TABLE studio_items (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    title TEXT NOT NULL,
    -- The first prompt, which a continued item's brief repeats.
    prompt TEXT NOT NULL,
    -- Optional. A project cannot be deleted while items belong to it, as with sessions.
    project_id UUID REFERENCES projects (id) ON DELETE NO ACTION,
    -- Where every file of the item is kept. A location in use cannot be deleted.
    storage_location_id UUID NOT NULL REFERENCES storage_locations (id) ON DELETE NO ACTION,
    -- The pinned thumbnail; NULL for the default. The foreign key follows studio_assets.
    thumbnail_asset_id UUID,
    -- Why the latest file could not be kept, such as the location's storage limit; cleared by
    -- the next file that is.
    pull_error TEXT,
    -- Soft delete: hidden from the grid, restorable.
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT studio_items_title_length CHECK (char_length(title) BETWEEN 1 AND 200),
    CONSTRAINT studio_items_prompt_length CHECK (char_length(prompt) BETWEEN 1 AND 100000),
    CONSTRAINT studio_items_pull_error_length CHECK (char_length(pull_error) BETWEEN 1 AND 2000)
);

SELECT diesel_manage_updated_at('studio_items');

-- The grid lists live items newest first.
CREATE INDEX studio_items_live_created_at_idx ON studio_items (created_at DESC) WHERE deleted_at IS NULL;
-- Serve the NO ACTION checks when a project or location is deleted.
CREATE INDEX studio_items_project_id_idx ON studio_items (project_id);
CREATE INDEX studio_items_storage_location_id_idx ON studio_items (storage_location_id);

-- A session belongs to Studio when it names an item; hard-deleting the item takes its
-- sessions, and with them their events and transcripts.
ALTER TABLE coding_sessions
    ADD COLUMN studio_item_id UUID REFERENCES studio_items (id) ON DELETE CASCADE;
CREATE INDEX coding_sessions_studio_item_id_idx ON coding_sessions (studio_item_id);

-- A Coding session always has a project; a Studio session has its item's, which is optional.
ALTER TABLE coding_sessions ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE coding_sessions
    ADD CONSTRAINT coding_sessions_project_required
    CHECK (studio_item_id IS NOT NULL OR project_id IS NOT NULL);

CREATE TYPE studio_asset_kind AS ENUM (
    'image',
    'model',
    'file'
);

-- A file an agent produced, pulled out of its workspace into the item's storage location.
-- Every version is kept: the next turn's render of the same path is a new row.
CREATE TABLE studio_assets (
    -- Generated by the API (UUIDv7), so ids sort by arrival.
    id UUID PRIMARY KEY,
    studio_item_id UUID NOT NULL REFERENCES studio_items (id) ON DELETE CASCADE,
    -- The session whose workspace it came from. A hard delete removes the item first.
    session_id BIGINT REFERENCES coding_sessions (id) ON DELETE SET NULL,
    kind studio_asset_kind NOT NULL,
    -- Where the agent wrote it, relative to the workspace's artifacts/ directory.
    artifact_path TEXT NOT NULL,
    content_type TEXT,
    size_bytes BIGINT NOT NULL,
    -- Hex SHA-256 of the contents, as the satellite reported it.
    sha256 TEXT NOT NULL,
    -- Where it is kept, relative to the location's directory.
    storage_path TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT studio_assets_version_unique UNIQUE (studio_item_id, artifact_path, sha256),
    CONSTRAINT studio_assets_artifact_path_length CHECK (char_length(artifact_path) BETWEEN 1 AND 1024),
    CONSTRAINT studio_assets_sha256_hex CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT studio_assets_size_unsigned CHECK (size_bytes >= 0)
);

CREATE INDEX studio_assets_session_id_idx ON studio_assets (session_id);

ALTER TABLE studio_items
    ADD CONSTRAINT studio_items_thumbnail_asset_id_fkey
    FOREIGN KEY (thumbnail_asset_id) REFERENCES studio_assets (id) ON DELETE SET NULL;

-- A prompt sent with a drawing. Both images are kept in the item's storage location.
CREATE TABLE studio_feedback (
    -- Generated by the API (UUIDv7); also names the workspace directory the drawing is sent in.
    id UUID PRIMARY KEY,
    studio_item_id UUID NOT NULL REFERENCES studio_items (id) ON DELETE CASCADE,
    session_id BIGINT REFERENCES coding_sessions (id) ON DELETE SET NULL,
    -- The turn it started, as the satellite named it.
    turn_id TEXT,
    prompt TEXT NOT NULL,
    -- What was drawn over; NULL once that asset is gone, or for a drawing over no asset.
    source_asset_id UUID REFERENCES studio_assets (id) ON DELETE SET NULL,
    -- The 3D viewer's camera orbit when the view was captured, as model-viewer writes it.
    camera_orbit TEXT,
    annotated_storage_path TEXT NOT NULL,
    annotated_size_bytes BIGINT NOT NULL,
    -- The view without the drawing.
    capture_storage_path TEXT,
    capture_size_bytes BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT studio_feedback_prompt_length CHECK (char_length(prompt) BETWEEN 1 AND 100000),
    CONSTRAINT studio_feedback_camera_orbit_length CHECK (char_length(camera_orbit) <= 200),
    CONSTRAINT studio_feedback_capture_complete
        CHECK ((capture_storage_path IS NULL) = (capture_size_bytes IS NULL))
);

CREATE INDEX studio_feedback_studio_item_id_idx ON studio_feedback (studio_item_id, created_at);

-- The location the New item form starts on. At most one.
ALTER TABLE storage_locations ADD COLUMN is_studio_default BOOLEAN NOT NULL DEFAULT false;
CREATE UNIQUE INDEX storage_locations_one_studio_default_idx
    ON storage_locations (is_studio_default) WHERE is_studio_default;
