-- Arsox satellites: remote agent workers Elysium drives. The bearer secret is sealed
-- by the API (XChaCha20-Poly1305, keyed by ELYSIUM_ENCRYPTION_KEY, bound to the row id)
-- before it reaches this table; Postgres only ever holds ciphertext.

CREATE TABLE satellites (
    -- Generated by the API (UUIDv7) so the id exists before the secret is sealed.
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    -- Base URL the API reaches the satellite at, such as http://arsox:8080.
    url TEXT NOT NULL,
    secret_encrypted BYTEA NOT NULL,
    -- Inactive satellites keep their sessions but are neither watched nor offered for new ones.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT satellites_name_unique UNIQUE (name),
    CONSTRAINT satellites_name_length CHECK (char_length(name) BETWEEN 1 AND 120),
    CONSTRAINT satellites_description_length CHECK (char_length(description) <= 2000),
    CONSTRAINT satellites_url_scheme CHECK (url ~ '^https?://' AND char_length(url) <= 2048),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT satellites_secret_sealed CHECK (octet_length(secret_encrypted) >= 41)
);

SELECT diesel_manage_updated_at('satellites');
