-- Changesets: batches of changes that anyone but the user proposes (Elysia, a coding
-- session's agent), which the user approves in whole, in part, or not at all before
-- anything is written. See docs/action-items.md.
--
-- An operation is stored as the JSON its proposer sent, validated by the API, so kinds can
-- be added without a migration. What applying it did is kept beside it, so the review shows
-- each outcome and a changeset can be undone.

CREATE TYPE changeset_state AS ENUM (
    -- Waiting for the user's review.
    'pending',
    -- Every operation was decided and the approved ones were applied.
    'applied',
    -- Every operation was rejected; nothing was written.
    'rejected',
    -- Applied, then undone as a whole.
    'undone'
);

-- The user's decision on one operation.
CREATE TYPE changeset_decision AS ENUM (
    'pending',
    'approved',
    'rejected'
);

-- What applying, and later undoing, did with one operation.
CREATE TYPE changeset_outcome AS ENUM (
    -- Not applied yet.
    'pending',
    'applied',
    -- Approved, but it could not be applied; `error` says why.
    'failed',
    -- Not applied: rejected, or it depends on an operation that was not applied.
    'skipped',
    -- Applied, then reversed by an undo.
    'undone'
);

CREATE TABLE changesets (
    -- Generated by the API (UUIDv7), so ids order changesets the way they were proposed.
    id UUID PRIMARY KEY,
    -- Who proposed it, in the actor form history records: elysia or session:<n>.
    proposer TEXT NOT NULL,
    -- The project a coding session proposed it in; NULL for Elysia.
    project_id UUID REFERENCES projects (id) ON DELETE SET NULL,
    -- One line from the proposer saying what the changeset is for.
    summary TEXT NOT NULL,
    state changeset_state NOT NULL DEFAULT 'pending',
    -- When it was applied or rejected; set exactly once it leaves pending.
    decided_at TIMESTAMPTZ,
    undone_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT changesets_proposer_shape CHECK (proposer ~ '^(elysia|session:[1-9][0-9]*)$'),
    CONSTRAINT changesets_summary_length CHECK (char_length(summary) BETWEEN 1 AND 500),
    CONSTRAINT changesets_decided_at_set CHECK ((decided_at IS NULL) = (state = 'pending')),
    CONSTRAINT changesets_undone_at_set CHECK ((undone_at IS NOT NULL) = (state = 'undone'))
);

SELECT diesel_manage_updated_at('changesets');

-- Serves the list of changesets waiting for review, and every list newest first.
CREATE INDEX changesets_state_idx ON changesets (state, id);

CREATE TABLE changeset_operations (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    changeset_id UUID NOT NULL REFERENCES changesets (id) ON DELETE CASCADE,
    -- The operation's place in its changeset, from 1. Operations apply in this order, and a
    -- later one names an earlier one by it.
    position INTEGER NOT NULL,
    -- The change, as the API validated it: an object whose `kind` names what it does.
    operation JSONB NOT NULL,
    -- Why the proposer wants it.
    reason TEXT NOT NULL,
    -- What it came from, where there is something: words quoted from a meeting or an email,
    -- and where they are.
    quote TEXT,
    source TEXT,
    decision changeset_decision NOT NULL DEFAULT 'pending',
    outcome changeset_outcome NOT NULL DEFAULT 'pending',
    -- Why it failed or was skipped.
    error TEXT,
    -- What applying it did: the ids it created and the values it replaced, which undo reads.
    result JSONB NOT NULL DEFAULT '{}',
    -- What undoing it did and could not do, such as a comment already posted to Jira; NULL
    -- until the changeset is undone.
    undo JSONB,

    CONSTRAINT changeset_operations_position_unique UNIQUE (changeset_id, position),
    CONSTRAINT changeset_operations_position_positive CHECK (position >= 1),
    CONSTRAINT changeset_operations_operation_kind
        CHECK (jsonb_typeof(operation) = 'object' AND operation ? 'kind'),
    CONSTRAINT changeset_operations_reason_length CHECK (char_length(reason) BETWEEN 1 AND 2000),
    CONSTRAINT changeset_operations_quote_length CHECK (char_length(quote) BETWEEN 1 AND 2000),
    CONSTRAINT changeset_operations_source_length CHECK (char_length(source) BETWEEN 1 AND 500),
    CONSTRAINT changeset_operations_error_length CHECK (char_length(error) <= 2000),
    CONSTRAINT changeset_operations_undo_object CHECK (jsonb_typeof(undo) = 'object'),
    CONSTRAINT changeset_operations_result_object CHECK (jsonb_typeof(result) = 'object'),
    -- Only an approved operation is applied, fails, or is undone.
    CONSTRAINT changeset_operations_outcome_approved
        CHECK (outcome NOT IN ('applied', 'failed', 'undone') OR decision = 'approved'),
    CONSTRAINT changeset_operations_error_set
        CHECK (error IS NULL OR outcome IN ('failed', 'skipped'))
);

-- The history entries an applied changeset recorded, and the ones its undo recorded, name it
-- as their source. Deleting a changeset would leave the entries without one, never lose them.
ALTER TABLE action_item_events
    ADD COLUMN changeset_id UUID REFERENCES changesets (id) ON DELETE SET NULL;

CREATE INDEX action_item_events_changeset_id_idx
    ON action_item_events (changeset_id)
    WHERE changeset_id IS NOT NULL;
