-- LLM provider credentials. The token is sealed by the API (XChaCha20-Poly1305,
-- keyed by ELYSIUM_ENCRYPTION_KEY, bound to the row id) before it reaches this table;
-- Postgres only ever holds ciphertext.

CREATE TYPE llm_type AS ENUM (
    'chatgpt_oauth',
    'chatgpt_api_token',
    'claude_api_token',
    'claude_code_oauth'
);

CREATE TABLE llms (
    -- Generated by the API (UUIDv7) so the id exists before the token is sealed.
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    type llm_type NOT NULL,
    secret_token_encrypted BYTEA NOT NULL,
    -- Lower numbers are tried first.
    priority INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    -- UTC instant; NULL means the credential does not expire.
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT llms_name_unique UNIQUE (name),
    CONSTRAINT llms_name_length CHECK (char_length(name) BETWEEN 1 AND 120),
    CONSTRAINT llms_description_length CHECK (char_length(description) <= 2000),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT llms_secret_token_sealed CHECK (octet_length(secret_token_encrypted) >= 41)
);

-- Serves "active credentials in priority order", the lookup every LLM call will make.
CREATE INDEX llms_active_priority_idx ON llms (priority, created_at) WHERE is_active;

SELECT diesel_manage_updated_at('llms');
