-- Coding sessions: Elysium's record of an Arsox thread. The thread itself (its state,
-- turns, and event history) lives on the satellite; this row is how Elysium finds it
-- again after a restart.

CREATE TABLE coding_sessions (
    -- Generated by the API (UUIDv7), and sent to the satellite as the create
    -- idempotency key, so a retried create never opens a second thread.
    id UUID PRIMARY KEY,
    -- Deleting a satellite forgets its sessions. The threads stay on the satellite
    -- until their idle TTL collects them.
    satellite_id UUID NOT NULL REFERENCES satellites (id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT coding_sessions_thread_unique UNIQUE (satellite_id, thread_id),
    CONSTRAINT coding_sessions_title_length CHECK (char_length(title) BETWEEN 1 AND 200),
    CONSTRAINT coding_sessions_thread_id_length CHECK (char_length(thread_id) BETWEEN 1 AND 200)
);

-- The overview lists newest first.
CREATE INDEX coding_sessions_created_at_idx ON coding_sessions (created_at DESC);

SELECT diesel_manage_updated_at('coding_sessions');
