-- Projects: what coding sessions are grouped under. Every session belongs to exactly one.

CREATE TABLE projects (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT projects_name_unique UNIQUE (name),
    CONSTRAINT projects_name_length CHECK (char_length(name) BETWEEN 1 AND 120),
    CONSTRAINT projects_description_length CHECK (char_length(description) <= 2000)
);

SELECT diesel_manage_updated_at('projects');

-- Sessions recorded before projects existed are gathered into one, so the column can
-- be required without discarding them.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM coding_sessions) THEN
        INSERT INTO projects (id, name, description)
        VALUES (uuidv7(), 'Unsorted', 'Sessions recorded before projects existed.');
    END IF;
END
$$;

-- A project that still has sessions cannot be deleted. Its sessions own running threads,
-- which must be destroyed deliberately, one session at a time. The default NO ACTION
-- rather than RESTRICT: both refuse the delete, but only NO ACTION reports SQLSTATE
-- 23503, which Diesel surfaces as a foreign key violation the API answers with 409.
ALTER TABLE coding_sessions ADD COLUMN project_id UUID REFERENCES projects (id) ON DELETE NO ACTION;
UPDATE coding_sessions SET project_id = (SELECT id FROM projects WHERE name = 'Unsorted');
ALTER TABLE coding_sessions ALTER COLUMN project_id SET NOT NULL;

CREATE INDEX coding_sessions_project_id_idx ON coding_sessions (project_id);
