-- The bundled Stalwart mail server's administrator. Stalwart issues it when the Email
-- settings page completes the server's setup, and the API signs in with it to create and
-- remove self-hosted mailboxes. The secret is sealed by the API (XChaCha20-Poly1305, keyed
-- by ELYSIUM_ENCRYPTION_KEY, bound to the row id); Postgres only ever holds ciphertext.

CREATE TABLE mail_servers (
    -- Generated by the API (UUIDv7) so the id exists before the secret is sealed.
    id UUID PRIMARY KEY,
    -- The domain chosen at setup: Stalwart's default domain and its administrator's.
    domain TEXT NOT NULL,
    admin_username TEXT NOT NULL,
    admin_secret_encrypted BYTEA NOT NULL,
    -- Setting the server up again replaces the row, so there is nothing to update.
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT mail_servers_domain_shape CHECK (
        domain ~ '^[a-z0-9.-]+\.[a-z0-9-]+$' AND char_length(domain) <= 253
    ),
    CONSTRAINT mail_servers_admin_username_length CHECK (char_length(admin_username) BETWEEN 1 AND 320),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT mail_servers_admin_secret_sealed CHECK (octet_length(admin_secret_encrypted) >= 41)
);

-- Elysium bundles exactly one mail server, so the table holds at most one row.
CREATE UNIQUE INDEX mail_servers_singleton ON mail_servers ((true));
