-- Jira Cloud credentials, one row per API token, with the projects and boards that token is
-- allowed to touch. The token is sealed by the API (XChaCha20-Poly1305, keyed by
-- ELYSIUM_ENCRYPTION_KEY, bound to the row id) before it reaches this table; Postgres only
-- ever holds ciphertext.

CREATE TABLE jira_credentials (
    -- Generated by the API (UUIDv7) so the id exists before the token is sealed.
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    -- The site's origin, such as https://acme.atlassian.net. The API validates and
    -- normalizes it; the shape check below is the backstop.
    site_url TEXT NOT NULL,
    -- The Atlassian account the token belongs to: the username half of HTTP basic auth.
    account_email TEXT NOT NULL,
    token_encrypted BYTEA NOT NULL,
    -- What Jira answered when the token was last checked. Elysium checks a token before it
    -- stores one, so these are never unknown.
    account_id TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    -- Every project, including ones added later, in which case the credential has no rows
    -- in jira_credential_projects. The same holds for boards.
    all_projects BOOLEAN NOT NULL DEFAULT FALSE,
    all_boards BOOLEAN NOT NULL DEFAULT FALSE,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT jira_credentials_name_unique UNIQUE (name),
    CONSTRAINT jira_credentials_name_length CHECK (char_length(name) BETWEEN 1 AND 120),
    -- Jira Cloud only: an https origin on atlassian.net, with no port, path, query, or
    -- fragment left on it.
    CONSTRAINT jira_credentials_site_url_shape
        CHECK (site_url ~ '^https://([a-z0-9][a-z0-9-]*\.)+atlassian\.net$'),
    CONSTRAINT jira_credentials_account_email_shape
        CHECK (account_email ~ '^[^@[:space:]]+@[^@[:space:]]+$'),
    CONSTRAINT jira_credentials_account_email_length CHECK (char_length(account_email) <= 320),
    CONSTRAINT jira_credentials_account_id_length CHECK (char_length(account_id) BETWEEN 1 AND 128),
    CONSTRAINT jira_credentials_display_name_length CHECK (char_length(display_name) <= 255),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT jira_credentials_token_sealed CHECK (octet_length(token_encrypted) >= 41)
);

SELECT diesel_manage_updated_at('jira_credentials');

-- The projects a credential may touch, unless it holds every project. The key and name are
-- stored alongside the id so the settings page renders a selection without calling Jira,
-- and so a bounded search can name the projects in JQL.
CREATE TABLE jira_credential_projects (
    jira_credential_id UUID NOT NULL REFERENCES jira_credentials (id) ON DELETE CASCADE,
    project_id TEXT NOT NULL,
    project_key TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (jira_credential_id, project_id),
    CONSTRAINT jira_credential_projects_key_unique UNIQUE (jira_credential_id, project_key),
    CONSTRAINT jira_credential_projects_project_id_shape CHECK (project_id ~ '^[0-9]{1,19}$'),
    -- A Jira project key is 2 to 255 characters: an uppercase letter, then uppercase
    -- letters, digits, and underscores. Keys are written into JQL, so the shape is enforced
    -- here as well as in the API.
    CONSTRAINT jira_credential_projects_project_key_shape CHECK (project_key ~ '^[A-Z][A-Z0-9_]{1,254}$'),
    CONSTRAINT jira_credential_projects_name_length CHECK (char_length(name) BETWEEN 1 AND 255)
);

-- The boards a credential may touch, unless it holds every board.
CREATE TABLE jira_credential_boards (
    jira_credential_id UUID NOT NULL REFERENCES jira_credentials (id) ON DELETE CASCADE,
    board_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    -- The board's project, when it has exactly one; NULL for a board spanning several.
    project_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (jira_credential_id, board_id),
    CONSTRAINT jira_credential_boards_board_id_positive CHECK (board_id > 0),
    CONSTRAINT jira_credential_boards_name_length CHECK (char_length(name) BETWEEN 1 AND 255),
    CONSTRAINT jira_credential_boards_project_key_shape
        CHECK (project_key IS NULL OR project_key ~ '^[A-Z][A-Z0-9_]{1,254}$')
);
