// Copyright © 2026 Jalapeno Labs

//! Postgres access through Diesel.
//!
//! `schema.rs` is generated by `diesel print-schema` from the migrations and is
//! the compile-time contract every query is checked against. Edit a migration,
//! never the schema file; `scripts/verify-migrations.sh` fails on drift.

pub mod migrations;
#[allow(
    clippy::wildcard_imports,
    missing_debug_implementations,
    reason = "generated by diesel print-schema"
)]
pub mod schema;

use diesel_async::AsyncPgConnection;

/// Async connection pool shared by every handler.
pub type Pool = diesel_async::pooled_connection::deadpool::Pool<AsyncPgConnection>;
