-- Comments written on an action item. See docs/action-items.md.

CREATE TABLE action_item_comments (
    -- Generated by the API (UUIDv7).
    id UUID PRIMARY KEY,
    action_item_id UUID NOT NULL REFERENCES action_items (id) ON DELETE CASCADE,
    -- Who wrote it, in the history's actor form: user, elysia, session:<n>, watcher:<provider>.
    author TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT action_item_comments_author_shape
        CHECK (author ~ '^(user|elysia|session:[1-9][0-9]*|watcher:[a-z][a-z0-9-]*)$'),
    CONSTRAINT action_item_comments_body_length CHECK (char_length(body) BETWEEN 1 AND 20000)
);

SELECT diesel_manage_updated_at('action_item_comments');

CREATE INDEX action_item_comments_action_item_id_idx
    ON action_item_comments (action_item_id, created_at);
