-- The history of action items and initiatives: one row per change, naming who made it.
-- See docs/action-items.md.
--
-- `kind` and `actor` are text rather than enums because later stages add kinds (links,
-- the watcher, changesets), and a value added to an enum cannot be used in the migration
-- transaction that adds it. The API owns the list of kinds; the database checks the shape.

CREATE TABLE action_item_events (
    -- Generated by the API (UUIDv7), so ids order entries the way they were written.
    id UUID PRIMARY KEY,
    -- The subject: an item, an initiative, or both for an item joining or leaving one.
    action_item_id UUID REFERENCES action_items (id) ON DELETE CASCADE,
    initiative_id UUID REFERENCES initiatives (id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    -- Who made the change: user, elysia, session:<n>, or watcher:<provider>.
    actor TEXT NOT NULL,
    -- What changed, shaped by kind; enough to show the change and to undo it.
    data JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT action_item_events_subject CHECK (action_item_id IS NOT NULL OR initiative_id IS NOT NULL),
    CONSTRAINT action_item_events_kind_shape CHECK (kind ~ '^[a-z][a-z_]{0,63}$'),
    CONSTRAINT action_item_events_actor_shape
        CHECK (actor ~ '^(user|elysia|session:[1-9][0-9]*|watcher:[a-z][a-z0-9-]*)$'),
    CONSTRAINT action_item_events_data_object CHECK (jsonb_typeof(data) = 'object')
);

CREATE INDEX action_item_events_action_item_id_idx
    ON action_item_events (action_item_id, id)
    WHERE action_item_id IS NOT NULL;

CREATE INDEX action_item_events_initiative_id_idx
    ON action_item_events (initiative_id, id)
    WHERE initiative_id IS NOT NULL;
