-- Mailboxes Elysium reads and sends mail from. The credential is sealed by the API
-- (XChaCha20-Poly1305, keyed by ELYSIUM_ENCRYPTION_KEY, bound to the row id) before it
-- reaches this table; Postgres only ever holds ciphertext.

CREATE TYPE mail_account_kind AS ENUM (
    'gmail',
    'outlook',
    'self_hosted'
);

CREATE TABLE mail_accounts (
    -- Generated by the API (UUIDv7) so the id exists before the credential is sealed.
    id UUID PRIMARY KEY,
    kind mail_account_kind NOT NULL,
    -- Stored lowercase, so uniqueness is case-insensitive.
    address TEXT NOT NULL,
    -- The name recipients see on sent mail. Empty means the bare address.
    display_name TEXT NOT NULL DEFAULT '',
    -- An OAuth refresh token for gmail and outlook; the mailbox password for self_hosted.
    credential_encrypted BYTEA NOT NULL,
    -- Stalwart's id for a self_hosted mailbox, needed to remove it there.
    external_id TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    -- The latest connection check. last_error is NULL when that check succeeded.
    last_checked_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT mail_accounts_address_unique UNIQUE (address),
    CONSTRAINT mail_accounts_address_shape CHECK (
        address ~ '^[^@\s]+@[^@\s]+$' AND address = lower(address) AND char_length(address) <= 320
    ),
    CONSTRAINT mail_accounts_display_name_length CHECK (char_length(display_name) <= 120),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT mail_accounts_credential_sealed CHECK (octet_length(credential_encrypted) >= 41),
    CONSTRAINT mail_accounts_external_id_self_hosted CHECK ((kind = 'self_hosted') = (external_id IS NOT NULL)),
    CONSTRAINT mail_accounts_last_error_length CHECK (char_length(last_error) <= 2000)
);

SELECT diesel_manage_updated_at('mail_accounts');
