-- External locations Elysium saves files to. The access key is sealed by the API
-- (XChaCha20-Poly1305, keyed by ELYSIUM_ENCRYPTION_KEY, bound to the row id) before it
-- reaches this table; Postgres only ever holds ciphertext.

CREATE TYPE storage_location_kind AS ENUM (
    'bunny'
);

-- Bunny Storage's regions. Each has its own endpoint, and a zone answers only on its own.
CREATE TYPE bunny_storage_region AS ENUM (
    'frankfurt',
    'london',
    'new_york',
    'los_angeles',
    'singapore',
    'stockholm',
    'sao_paulo',
    'johannesburg',
    'sydney'
);

CREATE TABLE storage_locations (
    -- Generated by the API (UUIDv7) so the id exists before the access key is sealed.
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    kind storage_location_kind NOT NULL,
    -- The storage zone and its region, for bunny.
    bunny_zone TEXT,
    bunny_region bunny_storage_region,
    -- The directory inside the location Elysium writes under, without leading or
    -- trailing slashes. Empty means the location's root.
    path_prefix TEXT NOT NULL DEFAULT '',
    -- Elysium's own cap on what it stores here, whatever the provider allows.
    storage_limit_bytes BIGINT NOT NULL,
    -- The storage zone password for bunny.
    access_key_encrypted BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT storage_locations_name_unique UNIQUE (name),
    CONSTRAINT storage_locations_name_length CHECK (char_length(name) BETWEEN 1 AND 120),
    CONSTRAINT storage_locations_bunny_fields CHECK (
        (kind = 'bunny') = (bunny_zone IS NOT NULL AND bunny_region IS NOT NULL)
    ),
    CONSTRAINT storage_locations_bunny_zone_shape CHECK (bunny_zone ~ '^[A-Za-z0-9-]{1,64}$'),
    CONSTRAINT storage_locations_path_prefix_shape CHECK (
        char_length(path_prefix) <= 1024 AND path_prefix !~ '(^/|/$|//)'
    ),
    CONSTRAINT storage_locations_storage_limit_positive CHECK (storage_limit_bytes > 0),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT storage_locations_access_key_sealed CHECK (octet_length(access_key_encrypted) >= 41)
);

SELECT diesel_manage_updated_at('storage_locations');
