-- GitHub tokens, one row per token. The token is sealed by the API (XChaCha20-Poly1305,
-- keyed by ELYSIUM_ENCRYPTION_KEY, bound to the row id) before it reaches this table;
-- Postgres only ever holds ciphertext.

-- How a token was issued. A classic token carries account-wide scopes; a fine-grained one
-- carries per-repository permissions, which GitHub does not report over the API.
CREATE TYPE github_token_kind AS ENUM (
    'classic',
    'fine_grained'
);

CREATE TABLE github_credentials (
    -- Generated by the API (UUIDv7) so the id exists before the token is sealed.
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    kind github_token_kind NOT NULL,
    token_encrypted BYTEA NOT NULL,
    -- What GitHub answered when the token was last checked. Elysium checks a token before
    -- it stores one, so these are never unknown.
    login TEXT NOT NULL,
    -- A classic token's scopes, as GitHub lists them in X-OAuth-Scopes: names separated
    -- by commas, such as 'repo,read:org'. Empty for a fine-grained token, whose
    -- permissions are per repository and are not reported over the API.
    scopes TEXT NOT NULL DEFAULT '',
    -- When GitHub stops accepting the token, or NULL for one that does not expire.
    token_expires_at TIMESTAMPTZ,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT github_credentials_name_unique UNIQUE (name),
    CONSTRAINT github_credentials_name_length CHECK (char_length(name) BETWEEN 1 AND 120),
    -- A GitHub login is 1 to 39 letters, digits, or hyphens.
    CONSTRAINT github_credentials_login_shape CHECK (login ~ '^[A-Za-z0-9-]{1,39}$'),
    CONSTRAINT github_credentials_scopes_shape CHECK (scopes ~ '^([^,\s]+(,[^,\s]+)*)?$'),
    -- Version byte + 24-byte nonce + 16-byte tag is the smallest possible sealed value.
    CONSTRAINT github_credentials_token_sealed CHECK (octet_length(token_encrypted) >= 41)
);

SELECT diesel_manage_updated_at('github_credentials');
